name: Unit Tests CI

on:
  push:
  pull_request:

env:
  raw_historical_county_inventory_data_save_location: ${{vars.RAW_HISTORICAL_COUNTY_INVENTORY_DATA_SAVE_LOCATION}}

jobs:
  run-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest
